👽️ Update: test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,8 +55,8 @@ jobs:
 
     
     - name: Test database connection
-      run: |  
-        nc -zv $DB_HOST $DB_PORT
+      run: |
+        timeout 5 bash -c "</dev/tcp/$DB_HOST/$DB_PORT" && echo "Connection successful" || echo "Connection failed"
 
     - name: Build Docker image
       run: |
